import { getTimeDifference } from "@/utils";
import { LANGUAGES } from "./language";
import { TECHNOLOGY_TITLE } from "./skills";

export const Experience = {
  [LANGUAGES.RU]: {
    title: "Опыт",
    items: [
      {
        company: "Менеджмент и финансы",
        location: "Москва",
        role: "Frontend-разработчик",
        duration: "Январь 2023 — По настоящее время",
        level: "Middle",
        workFormat: "Удаленно",
        skills: [
          TECHNOLOGY_TITLE.nextJs,
          TECHNOLOGY_TITLE.react,
          TECHNOLOGY_TITLE.typescript,
          TECHNOLOGY_TITLE.jsx,
          TECHNOLOGY_TITLE.tailwindCss,
          TECHNOLOGY_TITLE.git,
          TECHNOLOGY_TITLE.github,
        ],
        desc: "Разработка сайтов, ЛК и внутренних порталов для компаний. Используем собственный продукт компании в качестве бекенда с API для интеграции с нашими проектами. Технологический стек: Next.js, React, TailwindCSS",
      },
      {
        company: "Фриланс",
        location: "Москва",
        role: "Web-разработчик",
        duration: "Август 2021 — По настоящее время",
        level: "Middle",
        workFormat: "Удаленно",
        skills: [
          TECHNOLOGY_TITLE.javascript,
          TECHNOLOGY_TITLE.typescript,
          TECHNOLOGY_TITLE.react,
          TECHNOLOGY_TITLE.nextJs,
          TECHNOLOGY_TITLE.redux,
          TECHNOLOGY_TITLE.reduxToolkit,
          TECHNOLOGY_TITLE.git,
          TECHNOLOGY_TITLE.sass,
          TECHNOLOGY_TITLE.css,
          TECHNOLOGY_TITLE.html,
          TECHNOLOGY_TITLE.styledComponents,
          TECHNOLOGY_TITLE.csCart,
          TECHNOLOGY_TITLE.tilda,
        ],
        desc: "Реализация разнообразных проектов по разработке веб-приложений и интерфейсов. Специализация на создании адаптивных дизайнов, разработке пользовательских интерфейсов и интеграции с API. Использование современных технологий, включая React, Next.js, TailwindCSS и другие",
      },
      {
        company: "TopMarka1",
        location: "Нижний Новгород",
        role: "Frontend-разработчик",
        duration: "Октябрь 2022 — Ноябрь 2022 (2 месяца)",
        level: "Junior",
        workFormat: "Удаленно",
        skills: [
          TECHNOLOGY_TITLE.react,
          TECHNOLOGY_TITLE.redux,
          TECHNOLOGY_TITLE.jsx,
          TECHNOLOGY_TITLE.javascript,
          TECHNOLOGY_TITLE.sass,
          TECHNOLOGY_TITLE.git,
        ],
        desc: "В рамках проекта на полной занятости выполнялись задачи по верстке компонентов и разработке логики приложения. В работе использовались современные технологии: React, Redux для управления состоянием, роутинг, lazy loading и другие инструменты для оптимизации производительности",
      },
      {
        company: "21 sport nn",
        location: "Нижний Новгород",
        role: "Frontend-разработчик",
        duration: "Июль 2022 — Ноябрь 2022 (5 месяцев)",
        level: "Junior",
        workFormat: "Офис",
        skills: [
          TECHNOLOGY_TITLE.react,
          TECHNOLOGY_TITLE.redux,
          TECHNOLOGY_TITLE.reduxToolkit,
          TECHNOLOGY_TITLE.javascript,
          TECHNOLOGY_TITLE.jsx,
          TECHNOLOGY_TITLE.git,
          TECHNOLOGY_TITLE.sass,
        ],
        desc: "Разработка React-приложения для компании, занимающейся продажей оригинальной спортивной одежды. Основная задача заключалась в создании фронтенда на базе уже готового бекенда, разработанного на Nest.js. Проект стартовал летом и был завершен в ноябре, с дальнейшей поддержкой. В конце сентября, после ребрендинга и изменения концепции магазина, были внесены необходимые коррективы в проект",
      },
      {
        company: "АО «ГНИВЦ»",
        location: "Москва",
        role: "Frontend Стажер",
        duration: "Февраль 2022 — Март 2022 (2 месяца)",
        level: "Intern",
        workFormat: "Удаленно",
        skills: [
          TECHNOLOGY_TITLE.react,
          TECHNOLOGY_TITLE.mobX,
          TECHNOLOGY_TITLE.typescript,
          TECHNOLOGY_TITLE.nodeJs,
          TECHNOLOGY_TITLE.sass,
          TECHNOLOGY_TITLE.jsx,
        ],
        desc: "Во время стажировки в компании выполнялись индивидуальные задачи по JavaScript, TypeScript и верстке. Также было участие в командном проекте с использованием React, TypeScript и MobX. Команда состояла из 4 человек, включая главного разработчика и ментора",
      },
      {
        company: "СГУ им. П. Сорокина",
        location: "Сыктывкар",
        role: "Web-разработчик",
        duration: "Ноябрь 2019 — Июль 2020 (9 месяцев)",
        level: "Student",
        workFormat: "Офис",
        skills: [
          TECHNOLOGY_TITLE.javascript,
          TECHNOLOGY_TITLE.html,
          TECHNOLOGY_TITLE.sass,
          TECHNOLOGY_TITLE.php,
          TECHNOLOGY_TITLE.mySql,
        ],
        desc: "Индивидуальная работа над дипломным проектом и разработка внутреннего студенческого портала. Оба проекта были выполнены в области веб-разработки с использованием стека технологий: JavaScript, HTML, CSS, PHP и MySQL",
      },
    ],
  },

  [LANGUAGES.EN]: {
    title: "Experience",
    items: [
      {
        company: "Management and Finance",
        location: "Moscow",
        role: "Frontend Developer",
        duration: "January 2023 – Present",
        level: "Middle",
        workFormat: "Remote",
        skills: [
          TECHNOLOGY_TITLE.nextJs,
          TECHNOLOGY_TITLE.react,
          TECHNOLOGY_TITLE.typescript,
          TECHNOLOGY_TITLE.jsx,
          TECHNOLOGY_TITLE.tailwindCss,
          TECHNOLOGY_TITLE.git,
          TECHNOLOGY_TITLE.github,
        ],
        desc: "Development of websites, user accounts, and internal portals for companies. Using the company's own product as a backend with an API for integration with our projects. Technology stack: Next.js, React, TailwindCSS",
      },
      {
        company: "Freelance",
        location: "Moscow",
        role: "Web Developer",
        duration: "August 2021 – Present",
        level: "Middle",
        workFormat: "Remote",
        skills: [
          TECHNOLOGY_TITLE.javascript,
          TECHNOLOGY_TITLE.typescript,
          TECHNOLOGY_TITLE.react,
          TECHNOLOGY_TITLE.nextJs,
          TECHNOLOGY_TITLE.redux,
          TECHNOLOGY_TITLE.reduxToolkit,
          TECHNOLOGY_TITLE.git,
          TECHNOLOGY_TITLE.sass,
          TECHNOLOGY_TITLE.css,
          TECHNOLOGY_TITLE.html,
          TECHNOLOGY_TITLE.styledComponents,
          TECHNOLOGY_TITLE.csCart,
          TECHNOLOGY_TITLE.tilda,
        ],
        desc: "Implementation of various web application and interface projects. Specialization in creating responsive designs, developing user interfaces, and integrating with APIs. Utilized modern technologies including React, Next.js, TailwindCSS, and others",
      },
      {
        company: "TopMarka1",
        location: "Nizhny Novgorod",
        role: "Frontend Developer",
        duration: "October 2022 – November 2022 (2 months)",
        level: "Junior",
        workFormat: "Remote",
        skills: [
          TECHNOLOGY_TITLE.react,
          TECHNOLOGY_TITLE.redux,
          TECHNOLOGY_TITLE.jsx,
          TECHNOLOGY_TITLE.javascript,
          TECHNOLOGY_TITLE.sass,
          TECHNOLOGY_TITLE.git,
        ],
        desc: "Performed component styling and application logic development as part of a full-time project. Employed modern technologies: React, Redux for state management, routing, lazy loading, and other performance optimization tools",
      },
      {
        company: "21 sport nn",
        location: "Nizhny Novgorod",
        role: "Frontend Developer",
        duration: "July 2022 – November 2022 (5 months)",
        level: "Junior",
        workFormat: "Office",
        skills: [
          TECHNOLOGY_TITLE.react,
          TECHNOLOGY_TITLE.redux,
          TECHNOLOGY_TITLE.reduxToolkit,
          TECHNOLOGY_TITLE.javascript,
          TECHNOLOGY_TITLE.jsx,
          TECHNOLOGY_TITLE.git,
          TECHNOLOGY_TITLE.sass,
        ],
        desc: "Development of a React application for a company specializing in selling original sportswear. The main task was to create the frontend based on an already completed backend developed with Nest.js. The project started in the summer and was completed in November, with ongoing support. In late September, after a rebranding and change in the store's concept, necessary adjustments were made to the project",
      },
      {
        company: "AO GNIVC",
        location: "Moscow",
        role: "Frontend Intern",
        duration: "February 2022 – March 2022 (2 months)",
        level: "Intern",
        workFormat: "Remote",
        skills: [
          TECHNOLOGY_TITLE.react,
          TECHNOLOGY_TITLE.mobX,
          TECHNOLOGY_TITLE.typescript,
          TECHNOLOGY_TITLE.nodeJs,
          TECHNOLOGY_TITLE.sass,
          TECHNOLOGY_TITLE.jsx,
        ],
        desc: "During the internship, worked on individual tasks involving JavaScript, TypeScript, and styling. Also participated in a team project using React, TypeScript, and MobX. The team consisted of 4 members, including a lead developer and a mentor",
      },
      {
        company: "Syktyvkar State University",
        location: "Syktyvkar",
        role: "Web Developer",
        duration: "November 2019 – July 2020 (9 months)",
        level: "Student",
        workFormat: "Office",
        skills: [
          TECHNOLOGY_TITLE.javascript,
          TECHNOLOGY_TITLE.html,
          TECHNOLOGY_TITLE.sass,
          TECHNOLOGY_TITLE.php,
          TECHNOLOGY_TITLE.mySql,
        ],
        desc: "Individual work on a diploma project and development of an internal student portal. Both projects were in the field of web development, using the technology stack: JavaScript, HTML, CSS, PHP, and MySQL",
      },
    ],
  },
};
