import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Header } from "@/components";
import { cn } from "@/utils";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Roman Shcheglov",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('text-slate-700 dark:text-slate-100 font-medium text-lg',font.className)}>
        <Header />
        {children}
      </body>
    </html>
  );
}
