import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { FlyingElements, Header } from "@/components";
import { cn } from "@/utils";
import { LanguageProvider } from "@/context";
import { ThemeProvider } from "@/context/themeCtx";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Roman Shcheglov",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "text-slate-700 dark:text-slate-100 font-medium text-lg from-zinc-200 to-zinc-50 bg-gradient-to-tl dark:from-slate-900 dark:to-slate-700 min-h-screen max-w-screen-xl m-auto",
          font.className
        )}
      >
        <ThemeProvider>
          <LanguageProvider>
            <Header />
            <main className="flex flex-col items-center justify-center h-full">
              <div className="px-10 pt-12 pb-48 w-full flex items-center justify-center h-full">
                {children}
              </div>
            </main>
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
